dpi-tta-projects/pr-first-project

README.md
=> Add Dustin final project

README.md
=> add fidels project

README.md
=> Calvy projjy

README.md
Hiii approve me now!!! please..
=> brenda link

README.md
=> add Andre's project

README.md
=> added carman's first project

README.md
Added it back. I realized I had approved the change that removed it, sorry Aldo!
=> added Aldo's repo

README.md
=> adding my project description and links

README.md
=> added in mini project description

README.md
=> Attempting to add first project

README.md
=> added first project JP

README.md
=> Added Jeeho's project to list for 2024-2.1 cohort

README.md
=> add table header and nd row

README.md
=> added Aizat's project

README.md
=> added first project links

README.md
=> updated link-aizat

README.md
=> added Jan's project

README.md
=> added my first project

README.md
=> added first project

README.md
=> fixed first issue

README.md
=> added Max's first project

README.md
Closes #255 by adding project details and links.
=> Add Martinez Sunday Footy project

README.md
=> Add Maia's first project
